directories:
  output: dist-gui
  buildResources: build
appId: com.gemisoku.gui
productName: Gemisoku-GUI
files:
  - filter:
      - gui/**/*
      - node_modules/electron-store/**/*
      - node_modules/obs-websocket-js/**/*
      - node_modules/@google/generative-ai/**/*
      - node_modules/express/**/*
      - node_modules/electron-updater/**/*
      - '!node_modules/.cache'
      - '!node_modules/*/{test,tests,spec,specs,example,examples,*.md,*.MD,*.txt,*.TXT,*.yml,*.yaml,*.json.d.ts}'
      - '!node_modules/*/{README,readme,CHANGELOG,changelog,HISTORY,history,LICENSE,license,LICENCE,licence}*'
publish:
  - provider: github
    owner: eito54
    repo: Gemisoku-GUI
    releaseType: release
win:
  target: nsis
  icon: assets/logo.jpeg
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
mac:
  target: dmg
  icon: assets/logo.jpeg
  category: public.app-category.entertainment
linux:
  target: AppImage
  icon: assets/logo.jpeg
  category: Game
electronVersion: 36.3.2
